// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAI12wNFY2QkgUkdP-5GaiM28X35o8mg',
    appId: '1:956784069902:web:3f382ab7cf4d338b599b5f',
    messagingSenderId: '956784069902',
    projectId: 'ihelth-monitor',
    authDomain: 'ihelth-monitor.firebaseapp.com',
    storageBucket: 'ihelth-monitor.appspot.com',
    measurementId: 'G-HB3003X4S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dAuqnyGBARFGx3j65DItuCms_InSDTY',
    appId: '1:956784069902:android:e9d928ee6a0f4345599b5f',
    messagingSenderId: '956784069902',
    projectId: 'ihelth-monitor',
    storageBucket: 'ihelth-monitor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfnxyRXcD9j7GibVEjbJy1oUVxNVfsf2o',
    appId: '1:956784069902:ios:f2d80cd51c872b0a599b5f',
    messagingSenderId: '956784069902',
    projectId: 'ihelth-monitor',
    storageBucket: 'ihelth-monitor.appspot.com',
    iosBundleId: 'com.example.ihealthMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfnxyRXcD9j7GibVEjbJy1oUVxNVfsf2o',
    appId: '1:956784069902:ios:18eeb6e485929c54599b5f',
    messagingSenderId: '956784069902',
    projectId: 'ihelth-monitor',
    storageBucket: 'ihelth-monitor.appspot.com',
    iosBundleId: 'com.example.ihealthMonitor.RunnerTests',
  );
}
